name: american_mile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  gap: ^3.0.1
  flutter_screenutil: ^5.8.4
  cached_network_image: ^3.3.0
  dotted_border: ^2.0.0+3
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  animated_bottom_navigation_bar: ^1.3.0
  blur: ^3.1.0
  image_cropper: ^5.0.0
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  flutter_holo_date_picker: ^1.1.2+1
  flutter_speed_dial: ^7.0.0
  pinput: ^2.2.31
  webview_flutter: ^4.4.2
  easy_pdf_viewer: ^1.0.7
  map_launcher: ^3.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/img/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          style: italic
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica/Roboto-Black.ttf
        - asset: assets/fonts/helvetica/Roboto-Bold.ttf
        - asset: assets/fonts/helvetica/Roboto-Medium.ttf
        - asset: assets/fonts/helvetica/Roboto-Regular.ttf
          style: italic
    - family: Monoton
      fonts:
        - asset: assets/fonts/monoton/Monoton-Regular.ttf
          style: italic
    
  uses-material-design: true


