name: american_mile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  gap: ^3.0.1
  flutter_screenutil: ^5.8.4
  cached_network_image: ^3.3.0
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  animated_bottom_navigation_bar: ^1.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/img/
    
  uses-material-design: true


