name: american_mile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  gap: ^3.0.1
  flutter_screenutil: ^5.8.4
  cached_network_image: ^3.3.0
  dotted_border: ^2.0.0+3
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  animated_bottom_navigation_bar: ^1.3.0
  blur: ^3.1.0
  image_cropper: ^5.0.0
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  flutter_holo_date_picker: ^1.1.2+1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/img/
    
  uses-material-design: true


